name: Run tests on PR to dev

on:
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['4.4']

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install Dependencies
      run: npm ci

    - name: Eslint check
      run: npm run lint

    - name: Run Tests
      run: TOKEN_SECRET=NotTheRealSecret TEST_MONGODB_URI='mongodb://localhost:27017/feedback-app-test' npm test
      env:
        CI: true